name: Demo Workflow

on: 
  push:
    branches: [main]

env:
  OWN_SECRET_VALUE: ${{ secrets.OWN_SECRET }}

jobs:
  first-job:
    name: Run shell scrit
    runs-on: ubuntu-latest

    steps:
      - name: display string
        run: echo "Hello World"

      - name: display multiline text
        run: |
          node -v
          npm -v

      - uses: actions/checkout@v3

      - name: Display secret value
        run: |
          echo ${{ env.OWN_SECRET_VALUE }} >> ./secret.txt
          cat ./secret.txt